### ISSUE TITLE
Update my copy (fork) from original (upstream)

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#11]
As an editorial user, I want to get the latest changes to the master/parent/upstream version of the book I'm adapting, while retaining my changes, so that my version remains up to date.

**Comment by arthurattwell** [comment]
Me, 10 Oct 2016:

> Get latest changes from upstream origin, without overwriting my commits? Is this a git rebase or just a pull/fetch? Another approach may be to provide a diff in the review screen, perhaps by doing a pull request against the upstream master?

**Comment by SteveBarnett** [comment]
We need to show that there are updates available (but don't say tech-y things like "3 commits ahead of theotherone/master", and to alert the user that we'll be updating their copy.

**Comment by arthurattwell** [comment]
I've edited the title of this issue to reflect the fact that we need to be able to update a fork, but NOT an adaptation. And I've reiterated this thinking [here](https://github.com/electricbookworks/electric-book-gui/issues/7#issuecomment-300492200), too, in #7.

**Comment by arthurattwell** [comment]
[Moved to roadmap.](https://trello.com/c/heAjeR7s/35-update-fork)
