### ISSUE TITLE
Support for GitLab

### ISSUE THREAD

**Issue by GitBruno** [electricbookworks/electric-book-gui#114]
Is support for GitLab planned?

**Comment by GitBruno** [comment]
Good idea. It might be nice to map everything to an internal git-API, so everything sits at one place.

**Comment by craigmj** [comment]
GitBruno, there is already a git-like API internally, but there is a _big_ difference between _git_ and _github_: pull requests, your repos, invitations, etc are all _github_ ideas, not _git_ ideas.
