### ISSUE TITLE
Discuss submitted changes

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#12]
As an editorial user, I want to discuss a given change in a given submission with collaborators, so that we can work through issues in context.

**Comment by arthurattwell** [comment]
My comments from Trello thread:

> This is like GitHub's ability to comment on a given line of code in a pull request.

> [GitHub API docs](https://developer.github.com/guides/working-with-comments/) for this say:
> > To access comments on a Pull Request, you'll go through the Issues API. This may seem counterintuitive at first. But once you understand that a Pull Request is just an Issue with code, it makes sense to use the Issues API to create comments on a Pull Request.

**Comment by arthurattwell** [comment]
@SteveBarnett UI question: at this stage, we're not yet integrating GitHub comments into the EBM UI, though we've discussed maybe doing that later. As a short-term solution, do we have or can we add an explicit link to the comments thread on a PR? E.g. a 'See discussion on GitHub' link?

**Comment by SteveBarnett** [comment]
Yip, a "See discussion on GitHub" sounds like a good solution for now. I'll add a new Issue for this.
