### ISSUE TITLE
Web preview in editor

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#16]
As an editorial user, I want to see an instant preview of the web version of the file I'm editing, before I submit my changes for review or (as a managing editor) make them to my master version, so that I can know as I'm working how my content will be displayed to readers online.

**Terminology**

* 'Preview': the live, side-by-side preview of markdown rendered as HTML. I.e. this is not a full `jekyll serve`. 
* 'Output': the fully generated `jekyll serve`, output to the relevant format. Web in a separate tab, and screen-pdf, print-pdf and epub as downloads.

**Requirements**

Preview must render MathJax (see comments)

**Comment by arthurattwell** [comment]
Migrated from Trello, my comments:

**Oct 10, 2016 at 2:19 PM**
This has to handle Liquid tags, which include content tags, control flow tags, filters and includes. So we almost certainly can't provide an instant, WYSIWYG-type preview. We have to run Jekyll in the background when a user hits 'Save', and show them the new rendered HTML once Jekyll has finished incremental regeneration.

**Oct 11, 2016 at 9:42 AM**
Further to my last comment, we may want two kinds of preview: 

1. Live, instant side-by-side preview of kramdown as HTML, as in [kramdown.herokuapp.com/](http://kramdown.herokuapp.com/). With https://trello.com/c/7nxXmigi/4-syntax-highlighting-in-editor we can syntax-highlight Liquid tags in a way that shows that they are essentially variables, but not parse them and render their output. This preview uses the current `web.css` in `_html`.

2. Full web preview, which the user launches with a button click in a new tab. This is a full `jekyll serve` with incremental regeneration.

**Dec 17, 2016 at 2:04 PM**
Request form CORE team:

> Question: will editors be able to preview their work, as in how it will look on page, before they commit? Wendy points out this will be important for embedded LaTeX maths code, for example, that isn't WYSIWYG.
>
> Answer (from me): By phase 3, yes, but not in phase 1 (it is not part of phase 1's scope, which focused on Git version control, not the online editor). We do have a good idea of how we'll approach this technologically (essentially, embedding the MathJax script into our online markdown preview).

**Comment by SteveBarnett** [comment]
@craigmj Can we use GitHub Pages for the "Output" for web? The user already has a fork and will be pushing commits (which trigger `jekyll build`s). We "just" need to turn on the GH Pages option in settings. Looks like [there might be sort of something there for this later](https://developer.github.com/v3/repos/pages/)?

@arthurattwell Sorry if this is a stupid question, but: how does Pages *work* for the EB, given that you need to `jekyll serve` with an extra config (`configs/_config.web.yml`)?

**Comment by arthurattwell** [comment]
@SteveBarnett @craigmj We shouldn't use GH pages for our web output, because users should be able to test out their 'local' (as in on-the-EBM-server) changes before committing them.

As for serving on GH Pages: `_config.web.yml` is in most cases redundant, because it simply repeats the default settings in `_config.yml`. It's only useful to have it case you've changed something in `_config.yml`, e.g. your default `image-set` or `output` for some reason, but still want to use the output scripts to serve the site locally. (This is to some extent historical: in the earlier EB days, before the output scripts, I'd manually change the `output` in `_config.yml` before running `jekyll`. When I created the scripts, I wanted them to override any manual changes I might have left in there.)

So GH Pages ignores `_config.web.yml`, but only works if you haven't made a breaking change to `_config.yml`, like setting `output: epub`, which would break navigation.

**Comment by SteveBarnett** [comment]
Facepalm re using GHP! Of course.
And thanks for the explanation of config stuff.

**Comment by arthurattwell** [comment]
This is now working. We can pick up the discussion about in-editor markdown previews in #3.
