### ISSUE TITLE
Download epub

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#18]
As an editorial user, I want to download the book in its current epub forms (selecting EPUB2 or EPUB3), so that I can review a book's epub version, and publish it if it's ready.

**Comment by arthurattwell** [comment]
Me, Oct 10, 2016 at 2:19 PM: This probably depends on https://github.com/electricbookworks/electric-book/issues/59, where I'm working on a template-level batch/shell script.

**Comment by SteveBarnett** [comment]
@arthurattwell We discussed having "Download your epub ready files" (the results of a jekyll build with epub config) as a phase 1 option.

**Comment by arthurattwell** [comment]
@SteveBarnett @craigmj As explained at some length in https://github.com/electricbookworks/electric-book/issues/56#issuecomment-288744250, when we get to building finished-epub export, we won't worry about EPUB2. We only need EPUB3.

**Comment by arthurattwell** [comment]
[Moved to roadmap.](https://trello.com/c/zwbvead6/69-make-epubs)
