### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#19]
As an editorial user, I want to download the book in its current PDF forms (selecting print-PDF or screen-PDF), so that I can review a book's printable version, and publish it if it's ready.

**Comment by arthurattwell** [comment]
Craig/Mike have a prototype working I believe.

**Comment by SteveBarnett** [comment]
This means (for now at least) we need to have Prince running on the server. Details are in the `run-*` scripts in the [EB repo](https://github.com/electricbookworks/electric-book).

**Comment by arthurattwell** [comment]
@craigmj @SteveBarnett One of our challenges is keeping the output scripts that ship with the Jekyll template working in the same way as the output processes built into the GUI. We've already seen how the template's shell scripts moved on since Mike's early work on the GUI's web-based PDF generation, breaking his output in newer repos.

We have the same problem within the template already: we have to make sure that the Windows batch file does the same things as the Mac and Linux shell scripts. To tackle that problem, Steve and I are looking at replacing these shell scripts with one cross-platform Ruby script (see https://github.com/electricbookworks/electric-book/issues/98), which might live in the template as, say, `output.rb`.

On the GUI server, might it be possible to run the same Ruby script to trigger PDF/web/epub output? That is, instead of running, say, `jekyll build` from Go, you run `output.rb`, which itself then runs Jekyll, Prince, Phantom, etc. 

This may not be feasible, but if it were, then for all output options we'd only have to maintain `output.rb`. 

Then it would be much easier to (1) keep output options consistent between the super-user-offline-use of the EBW and the layperson's GUI, and (2) let the GUI output files from different repos whose `output.rb` may differ over time.

**Comment by arthurattwell** [comment]
Update: This is currently working on staging (http://demo.electricbook.works) for untranslated books in a `book` folder.

**Comment by arthurattwell** [comment]
We can now download a print PDF from the EBM, so this issue is fixed.

In addition to the discussion at the template repo, I've created #67 for the bold idea of a single output script for both offline template and EBM.
