### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#2]
As any user, I want to log in so that I can manage my books.

Note: OAuth with GitHub

**Comment by SteveBarnett** [comment]
It would be good to set the GUI's permission's more granularly.

Current:

```
Repositories
Public and private
This application will be able to read and write all public and private repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
```

😱 !

**Comment by SteveBarnett** [comment]
Also: we want to have some kind of log in page so that we can tell users that we're about to ask them to authorise the app on GitHub, and maybe have a "You will need a GitHub account, sign up here." kind of thing.

**Comment by SteveBarnett** [comment]
@craigmj how do we populate https://github.com/electricbookworks/electric-book-gui/blob/master/electricbook.yml ? Thanks! :)

**Comment by SteveBarnett** [comment]
@craigmj Can you add a placeholder page to the repo for me, please, that I can fill in?
I'll need a "we need auth" (with a button to tap to send us off to GitHub to ask for auth) and a "we have auth" section.

**Comment by SteveBarnett** [comment]
@arthurattwell I think it would be nice to have this for demo on Tuesday, so I've added the "current" label. I think it'll start to make the EBM feel more solid and proper-application-y. Do you agree?

**Comment by SteveBarnett** [comment]
@craigmj I have some questions about auth.

1. It currently shows **your** GitHub avatar, I think because you're the repo owner. What's the best way to change this? Ideally, we should show the [EBW](https://github.com/electricbookworks) [avatar](https://avatars1.githubusercontent.com/u/7754562?v=3&s=200) (and maybe later, a fancy EBM logo \o/ ).
2. Can we simplify the permissions list? At the moment, it asks for All The Things, and we should only ask for what we need. It will look less 🙀 .

**Comment by craigmj** [comment]
1. Looks like I can just set as I wish-I've set to EBW.

2. I want to leave it on all for right now - we can crop to what we
actually need down the line, when we know what we're actually using.

**Comment by SteveBarnett** [comment]
Re 1: can you push that change, please, so that I can test it?

Re 2: I think we kinda know what we need, right? Code and Pull requests. We don't need access to 
Issues, Wikis, Settings, Webhooks and services, or Deploy keys.
We want to change this so that it looks more friendly and less scary (in terms of what it's asking for)

**Comment by craigmj** [comment]
It's not a change in git, it's a reconfigure seeing up the app on github.
Has it not changed?
C

**Comment by SteveBarnett** [comment]
Here's what  I see.

When I auth:
![screenshot 2017-03-23 09 47 42](https://cloud.githubusercontent.com/assets/1239497/24237361/a6dcbf7a-0fae-11e7-8fac-03c029751807.jpg)

My Authorized applications page:
![screenshot 2017-03-23 09 50 50](https://cloud.githubusercontent.com/assets/1239497/24237268/46991492-0fae-11e7-9536-fae694cf5d12.jpg)

Do I need to do change some settings somewhere? :)

**Comment by craigmj** [comment]
Ah, looks like I set the wrong application logo. Please try again!

C

**Comment by SteveBarnett** [comment]
The logo looks good in my Authorised Apps page now (although it's "electricbooks"), but hitting the auth page from the app still shows the old logo. Maybe it's caching?

**Comment by arthurattwell** [comment]
@SteveBarnett +1 on having this for Tuesday, thanks. Shout if you need me to provide or weigh in on the landing-page and/or its copy.

**Comment by craigmj** [comment]
You can edit `public/landing.html`.

**Comment by craigmj** [comment]
Far as I can tell I cannot control app permissions at all... can't seem to find it in Github, not even on creating a new app...

**Comment by SteveBarnett** [comment]
@craigmj All or nothing on repos, huh? Okay, it is what it is. ¯\_(ツ)_/¯

@arthurattwell can you have a look at the copy on https://github.com/electricbookworks/electric-book-gui/pull/40, please?

**Comment by SteveBarnett** [comment]
https://github.com/electricbookworks/electric-book-gui/pull/40 is merged in and the logo thing above is done, so we're a go 🚀
