### ISSUE TITLE
Edit any of the files

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#27]
Related to https://github.com/electricbookworks/electric-book-gui/issues/3 . Currently the GUI only shows the contents of `book/text`.

**Comment by SteveBarnett** [comment]
Also: we could use a `_prose.yml` to exclude really dodgy stuff from the listing, but most stuff needs to be shown.

For later, we could show / hide stuff based on roles?

**Comment by SteveBarnett** [comment]
Other files: sass!

**Comment by SteveBarnett** [comment]
It seems like sub-folders aren't picked up either at the moment, which we need for translations (https://github.com/electricbookworks/electric-book-gui/issues/10).

**Comment by arthurattwell** [comment]
@SteveBarnett This is fixed, right? Shall we close?

**Comment by SteveBarnett** [comment]
@arthurattwell Yes. Although we might need to add more syntax highlighting if we're going to allow editing of Sass / CSS.

**Comment by arthurattwell** [comment]
@SteveBarnett Thanks. We'll pick up the syntax highlighting stuff in #3 and #17.
