### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#29]
At the moment log off redirects the user back to their GitHub profile.

- We should call it log out (since we have log in)
- we should redirect them to an EBM landing page. From the users' point of view, they've been using the EBM, not GitHub. That's what they're logging out of.

**Comment by craigmj** [comment]
Done, I think? (On latest build that you should have).

**Comment by SteveBarnett** [comment]
Fixed in https://github.com/electricbookworks/electric-book-gui/commit/67bf90ec59ea12b20cb22eccc9f8a23a66a510e0
