### ISSUE TITLE
Improve file-renaming UX

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#30]
We should let users edit filenames, so that they can change them or fix typos (he said from personal experience).

**Comment by arthurattwell** [comment]
This is working on demo, but we need a tweak to the UX.

Once you've renamed a file, the old-named file remains in the editor, and the new-named file is added to the bottom of the file list. If you click 'Save' with the old-name file still in the editor, that file is added back. And, as a result, you have both old-name and new-name versions of the file in the repo. I then have to manually delete the old-name file.

To avoid this, after renaming we should automatically switch the open file in the editor from the old-name file to the new-name one.

**Comment by arthurattwell** [comment]
This was fixed a while ago.
