### ISSUE TITLE
Repo list doesn't show all the repos

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#33]
It looks like stops at 30?
For people who touch a lot of repos (like me!) this means I sometimes don't see the one that I want to work on.

**Comment by arthurattwell** [comment]
Now that we're filtering to only show Electric Book repos, this is hard to test.

@craigmj Do you know off the top of your head whether this limitation still exists, or shall we close the issue and open a new one if/when we see this limitation affecting users in the wild? If it will be useful, I'm happy to create a big bunch of repos to test it.

**Comment by arthurattwell** [comment]
I'm closing this for now, since it's not a current issue in any testing.
