### ISSUE TITLE
Missing `package.json`

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#34]
@craigmj I suspect you might have it lurking in a different directory or something?

Please add it to the repo so that @arthurattwell and I can easily install the stuff needed for running the gulpfile. Thanks!

**Comment by craigmj** [comment]
Hmm... I don't actually have it. I presume it should be generated by npm when installing the pieces for the gulpfile? (I actually do this with a little tool I have for fetching npm pieces... I can share that, and perhaps change it to create the package.json at the same time...)

**Comment by craigmj** [comment]
Done.
