### ISSUE TITLE
New page and layout for book / repo

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#37]
At the moment, /repo/:repo_name takes you directly to the editor. From the wireframes we did (https://github.com/electricbookworks/electric-book-gui/issues/1#issuecomment-273514475), we want the book / repo URL to be a bit more like GitHub's: it should show commits, incoming PRs, and things.

![4 book alternate 323f](https://cloud.githubusercontent.com/assets/1239497/24201474/c93b65b2-0f18-11e7-962e-8d36654108c8.png)

**Comment by arthurattwell** [comment]
We now have this book-dashboard in progress. Wireframes maintained in #1 (see [here for this one]( https://github.com/electricbookworks/electric-book-gui/issues/1#issuecomment-290144098)). Specific enhancements can be new issues.
