### ISSUE TITLE
Save and commit

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#4]
As an editorial user, I want to save my changes as I work, and after a bunch of saves, commit all my saved changes along with a short message about those changes. Before I close my browser window or navigate away, I want to be reminded if I have not saved my changes.

I'm saving continually so that I have peace of mind that my changes won't get lost if my connection dies. And I'm grouping changes with short messages so that I have a record of my changes to my version of the book.

**Comment by arthurattwell** [comment]
My comment on Trello from 10 Oct 2016:

> Here we're trying to provide the usefulness of the Git process of saving and committing to one's own branch. Ever user should always be working in their own branch. We'll deal with submitting changes to master elsewhere.

**Comment by arthurattwell** [comment]
From recent documentation: 

> **User workflow**
> In our system, a managing editor ‘owns’ a repository of one or more books. This repository contains the master version of those books. Contributors (who might be authors, editors or other consultants) cannot change that master version directly. A contributor uses the Electric Book web interface to see and edit their own personal version of the book, and then submits their changes to the managing editor. The managing editor then reviews those submissions, accepting or rejecting changes before saving a new version to the master repository. There may be more than one managing editor for a repository. The history of all changes is recorded as a paper trail of contributions.
> 
> **Technical explanation**
> In technical terms, behind the scenes: when a contributor opens a book in the interface, it creates a new fork of the repository in their own GitHub account. While editing, they save their changes locally on the Electric Book server. When they are ready to send their changes to the managing editor, a single command commits the changes to their fork’s master branch and creates a pull request to the upstream master. That is, we combine a commit and a PR into one user action. We use the GitHub API to record that pull request and notify the repo administrators (managing editors). The managing editor can then see a diff of the changes and can copy their selected changes into their original, master branch as a new commit. (I.e. they do not perform a direct merge of the downstream changes into the upstream repo, since the managing editor must be able to copy changes at a more granular level than a single commit, which Git does not provide for. The pull request still records the history of the contributor’s original, submitted changes, and its HEAD commit is recorded.) The managing editor then closes the pull request. All of this technical Git terminology is hidden from the user.

**Comment by SteveBarnett** [comment]
Bug: when there are no commits and you try and make a PR, there's a system error. There should be a human-friendly page saying that you need to make some changes before requesting a review.

**Comment by SteveBarnett** [comment]
One of the big selling points of the EBM is the paper trail. At the moment, Saves in the GUI make a commit, with the commit message "automatic message." We need to figure out a way of having more relevant messages without (necessarily) forcing the user to enter them. Maybe just "Edited `{{ title }}`" would be better for now?

**Comment by arthurattwell** [comment]
Based on subsequent discussion, we're going to require a commit message with every commit. We're working on the user terminology, but likely something like:

* the 'save' button saves the file you're editing, but doesn't commit
* the 'Make a snapshot of my book' button does a commit of the whole repo and requires a commit message.
