### ISSUE TITLE
Add note in README about `~/.ebw.yml` GitHub Personal access tokens

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#45]

**Comment by arthurattwell** [comment]
@SteveBarnett @craigmj Can we add to this note which Scopes are required for the token? I realise this might change as we build. I'm assuming `repo` and `user`?

![image](https://cloud.githubusercontent.com/assets/1053331/24415720/ae954bdc-13e2-11e7-814f-ad42239145e5.png)

**Comment by craigmj** [comment]
Sure, but I've not yet found a place where you can set the scopes you
require, at least not on a per-application basis. I guess that's
intended to be accomplished by the user, but at present the application
itself only requests 'repo'.

C

**Comment by arthurattwell** [comment]
Thanks, I've made that note in #48.
