### ISSUE TITLE
Discuss submitted changes on GitHub

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#47]
As a stopgap for [discussing in the EBM](https://github.com/electricbookworks/electric-book-gui/issues/12), we're going to have a link out to the discussion of the PR on GitHub.

This should probably be a link on

- Dashboard, with PRs
- Book page, with PRs
- the PR page

**Comment by arthurattwell** [comment]
Our PRs do now include a link to the conversation on GitHub.

![image](https://cloud.githubusercontent.com/assets/1053331/25947401/94baa98e-364f-11e7-87ab-e263f28f4937.png)

@SteveBarnett are you happy to close this, or do you want to keep this issue to implement this link in other places in the UI, as listed [above](https://github.com/electricbookworks/electric-book-gui/issues/47#issue-217468399)?

**Comment by SteveBarnett** [comment]
@arthurattwell Hmm.

✔️ We have it on the PR page.
✔️ We've switched to a leaner design for the dashboard, so we don't need it there anymore.
✖️  There currently is no [book page as per the wireframes](https://github.com/electricbookworks/electric-book-gui/issues/1#issuecomment-290144098) (which has a short PR list), so there's no link there.

I'm guessing that the book page isn't going to happen, though, so we can close this issue?

**Comment by arthurattwell** [comment]
@SteveBarnett If I understand correctly, the book page is the one that Jackie is working on, which Craig described this morning?

**Comment by arthurattwell** [comment]
We now have the book page with its list of PRs. We don't need a link to discussion there (even per the wireframes), but only from the PR page itself. So I'm closing this issue.
