### ISSUE TITLE
Submit changes for review

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#5]
As an editorial user, I want to submit my changes to the managing editor for review, so that they can decide what to accept into the master version.

**Comment by arthurattwell** [comment]
See https://github.com/electricbookworks/electric-book-gui/issues/4#issuecomment-270902976

**Comment by SteveBarnett** [comment]
Also see https://github.com/electricbookworks/electric-book-gui/issues/4#issuecomment-286083447

**Comment by SteveBarnett** [comment]
Once a Pull Request has been made, there should be explicit confirmation of this. At the moment you're returned to where you were editing.

Also, your changes have disappeared. Is this just a caching problem? going to the repo list, then back in seems to fix this.

@arthurattwell I can't remember what happening in our testing just now: do additional commits (on your fork) update the PR?

**Comment by SteveBarnett** [comment]
For later: the repo list should show your repos and any repos you have access to.

**Comment by arthurattwell** [comment]
@SteveBarnett Yes, new commits (just clicking the 'save' button, not 'Submit changes for review') do add to the PR, e.g. https://github.com/SteveBarnett/Checklists/pull/1/commits/ea20fa75eb9b45033d22ecd61854916fec4d0d27

**Comment by arthurattwell** [comment]
Moved to [roadmap](https://trello.com/c/s1pcwg7x/36-submit-changes-for-review).
