### ISSUE TITLE
Filter repo list for just Electric Books

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#51]
From a chat with @arthurattwell: the repo list could get quite long for some users, and it would be good to talk (correctly) about "Books" the whole time (and not have any other repos) showing in the list. There are a couple of ways that we could do this using [repo / contents](https://developer.github.com/v3/repos/contents/#get-contents) of the GitHub API. We should start with a quick and easy version to get it working, then improve on it while we're building the EBW.

Some ideas for how:

- a `.electric-book` file. If it's there, it's an Electric Book and should be shown in the list.
- a `.eb-version` file with the version number in.
- look for "Electric Book" in the `_config.yml`
- make a new `.electric-book.yml` that has the version number and other stuff in it, and look for `ebversion`

@craigmj What's the best way to do (the first version of) this?

**Comment by arthurattwell** [comment]
This is now working. I believe it's based on the presence of `_data/meta.yml`, @craigmj?
