### ISSUE TITLE
Have a friendly URI structure

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#63]
A friendly, hackable, URI structure makes for a more usable application. Here’s an idea of what the routes could be, with a sort of RESTful flavour.

| Route | Content | Style Guide Reference |
|---|---|---|
| `/` | Request Auth on GitHub or show Repo list if authed | [#dashboard](http://localhost:16101/style-guide.html#dashboard)
| `/repositories` | Shows a list of repos, much like the dashboard | [#dashboard](http://localhost:16101/style-guide.html#dashboard)
| `/repositories/{reponame}` | Show a single repo. Shows supporting info: when a fork sync is required; PRs (opens and closed); a file list; recent changes list; recent commits list. | Fork sync shows an [info #notification](http://localhost:16101/style-guide.html#notification); [#pull-requests](http://localhost:16101/style-guide.html#pull-requests); [#file-list](http://localhost:16101/style-guide.html#file-list); [#make-a-commit](http://localhost:16101/style-guide.html#make-a-commit) |
| `/repositories/new` | For making a fork, a translation, or an adaptation | [#make-a-new-copy](http://localhost:16101/style-guide.html#make-a-new-copy) |
| `/repositories/{reponame}/{filename}` | Shows the editor, editing filename. |  |
| `/repositories/{reponame}/new` | Shows a small form for adding a new file. |  |
| `/repositories/{reponame}/commits` | Shows a list of commits. |  |
| `/repositories/{reponame}/commits/{hash}` | Shows a commit. |  |
| `/repositories/{reponame}/commits/new` | Shows a commit form. | [#make-a-commit](http://localhost:16101/style-guide.html#make-a-commit) |
| `/repositories/{reponame}/submissions` | Shows a list of PRs | [#review-pull-requests](http://localhost:16101/style-guide.html#review-pull-requests) |
| `/repositories/{reponame}/submissions/new` | Shows a form to submit a PR |  |
| `/repositories/{reponame}/submissions/{id}` | Shows a PR | [#review-pull-requests](http://localhost:16101/style-guide.html#review-pull-requests) |

@arthurattwell What do you think?

**Comment by arthurattwell** [comment]
The URL structure @craigmj has implemented seems friendly, so I'm closing this for now. We can revisit as an enhancement later if/when appropriate.

**Comment by SteveBarnett** [comment]
@arthurattwell Happy with closing it for now, but we might want to check for things like `pull`, which [we'd like to try and avoid](https://github.com/electricbookworks/electric-book-gui/blob/master/README.md#using-friendly-terminology).
