### ISSUE TITLE
Create an adaptation

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#7]
As an editorial user, I want to create my own, new version of a book by clicking a button, so that I can create adaptations.

**Comment by arthurattwell** [comment]
Migrated from Trello. Thread, all my comments:

**Oct 10, 2016 at 2:19 PM**
This is probably a fork of a repository. What if there are more than one Jekyll sites in a repo? Do we fork the repo but only copy the relevant book?

**Nov 29, 2016 at 3:05 PM**
This was not planned for phase 1, but we've built it in as a side-effect of building a fork-based (not branch-based) model for content editing.

**Comment by SteveBarnett** [comment]
Note: don't pre-fill the base repo. Allow people to paste in the repo URL (without the trailing `.git`).

**Comment by SteveBarnett** [comment]
Currently the forking is two steps: there's an interstitial "confirm" page. It's fine for this to be skipped and make a fork immediately after clicking "Create" on the repo list page.

**Comment by SteveBarnett** [comment]
In the repo list, we could have a "Make an adaptation of this" button.

**Comment by arthurattwell** [comment]
@SteveBarnett Just to clarify: If the repo list only shows your own repos (as it does now), a 'Make an adaptation of this' button wouldn't work because GitHub doesn't let you fork a repo already in your account -- IIRC?

But if we added to the repo list any repos that you have access to (as a collaborator according to GitHub), but had not yet forked, then we could indeed have a 'Make an adaptation of this' button.

**Comment by arthurattwell** [comment]
@craigmj @SteveBarnett

This is to clarify what we mean by 'adaptation'. We use a GitHub fork for both:

1. editing a book as a contributor and 
2. for creating an adaptation.

An adaptation is much more than an edit. It is a whole new version of the book, where content changes. So, as a user, in creating one I don't want to submit my changes to the parent/upstream version.

So, since anyone who opens a book is forking it, 'creating an adaptation' is not equivalent to 'fork this repo'. It is equivalent to 'break the relationship between this repo and its parent/upstream'. 

What does that mean on GitHub? Do we simply remove the upstream remote, as [this gist suggests](https://gist.github.com/paulbooker/1650131)? [Other](http://webapps.stackexchange.com/questions/89672/remove-upstream-from-forked-repository-on-github) [people](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub) have said that doesn't work, and you need to create a whole new repo. 

If we can't do this easily in Git, then I believe creating an adaptation means making a copy of the files in the repo, without the Git history, in a new repo.

**Comment by craigmj** [comment]
I think our adaptation is essentially what we do when we start a new
book. Our new book starts from the electirc-book repo, but an adaptation
could as-easily start from CORE. It's a new repo, but with the assets of
the origin repo, except there's no git / github link between repos... ?

C

**Comment by arthurattwell** [comment]
Thanks, @craigmj, then the plumbing already works? When the backend creates a new repo, the default can be `electricbookworks/electric-book`, unless specified otherwise.

If so, then in the UI, @SteveBarnett: beside the option to [create a new book](https://github.com/electricbookworks/electric-book-gui/issues/22), shall we add the option of adapting an existing one?

1. 'New book' button --> creates new repo with assets from `electric-book`
2. 'Adapt an existing book' button --> asks user to identify source repo,* then creates new repo with assets from that source repo.

\* For identifying the source repo, we should allow users to enter several variations on how GitHub identifies repos:

- `ownername/reponame`
- `https://github.com/ownername/reponame`
- `https://github.com/ownername/reponame.git`
- `git@github.com:ownername/reponame.git`

**Comment by arthurattwell** [comment]
@SteveBarnett and I were discussing this again today, so just to confirm our thinking: *an 'adaptation' is a completely new, separate project*. It uses the files from its parent as a starting point (an initial commit), but not its parent's git history nor any connection to its parent repo (e.g. as a remote/upstream).

This is because, if I'm a user working on an adaptation, I don't want my changes overwritten by changes to the original that I'm adapting. And users on the original version don't want my pull requests.

**Comment by arthurattwell** [comment]
Moved to [roadmap](https://trello.com/c/ZdLU4iyl/40-create-adaptation).
