### ISSUE TITLE
Change 'Close changes' to 'Mark all changes resolved'

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#70]
When reviewing a PR, below the file list there is a 'Close changes' button. While testing, I thought this meant 'close the page', but it actually closes the PR on GitHub.

![image](https://cloud.githubusercontent.com/assets/1053331/26162835/1f88b8a8-3b28-11e7-9c3a-10e4ce0f2398.png)

Let's reduce confusion by renaming that button more dramatically. I suggest 'Mark all changes resolved'.

@SteveBarnett @craigmj Unless you have other suggested wording or behaviour?

I don't think we have a similar button or solution for this in [Steve's UI wireframes](https://github.com/electricbookworks/electric-book-gui/issues/1#issuecomment-273514475). We do need a button that closes the PR though. Steve, if you agree, should we add it to the wireframes?

**Comment by SteveBarnett** [comment]
@arthurattwell In [our terminology guide](https://github.com/electricbookworks/electric-book-gui/blob/master/README.md#using-friendly-terminology), we talk about this page as being a **submission for review** and **changes submitted for review**, so I think we need to use words that match that. We also need words for the 👍 state.

The technical terms we use are "Merge pull request" and "Close pull request." Our non-technical terms should talk about what that means in terms of the submission that's being reviewed. The wireframes currently show:

- "Close pull request" -> "Update master version"
- "Merge pull request" -> "Don't update master version"

But maybe we should change that to:

- "Close pull request" -> "Reject this submission" or "Reject these changes"
- "Merge pull request" -> "Accept this submission" or "Accept these changes"

And then:

1. I'll add these to README once we decide here.
2. I propose to update the wireframes when I start on [adding the GUI tests](https://github.com/electricbookworks/electric-book-gui/issues/69) on Monday. Is good?

**Comment by arthurattwell** [comment]
This UI has changed completely now that we have a Mergely editor for this. We'll improve that UI separately.
